function [depthOrd, pFOrd, pTauOrd, pHLOrd, pFLOrd, psLOrd, ...
          depthExt, pFExt, pTauExt, pHLExt, pFLExt, psLExt, ...
          pScanOrd, pScanExt, pScanFF] = ...
         reoCalculate(hLib, mfoData, H, Temp, Dens, M, freq, harms, pTauL, mode, c, b, posR, posL)

if ~exist('mode', 'var')
    mode = 3;
end
if ~exist('c', 'var') || isempty(c)
    c = 0;
end
if ~exist('b', 'var') || isempty(b)
    b = 8.5;
end
if ~exist('posR', 'var')
    posR = 0;
end
if ~exist('posL', 'var')
    posL = 0;
end

[depthOrd, pFOrd, pTauOrd, pHLOrd, pFLOrd, psLOrd, ...
 depthExt, pFExt, pTauExt, pHLExt, pFLExt, psLExt, ...
 pScanOrd, pScanExt, ...
 ~, ~, ~, ~, ~, pScanFF, ...
 rc, ...
 pTimes, pQuanc82Cnt, pLaplas90Cnt, pLaplasCnt ...
] = gstCalcMapAll(hLib, ...
                     H, Temp, Dens, ...
                     M, freq, harms, pTauL, ...
                     mode, c, b, mfoData.R, posR-1, posL-1);

if rc ~= 0
    disp('***** Some problems during calculation *****');
end

end
